name = "Westridge"
author = "Alexander Keith"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "853cda76cd4b132a7d4ab691ba8c0641373facd0f7afbd90fb8fc6996c342b10"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
